### ISSUE TITLE
Connecting to a remote stratum server

### ISSUE THREAD

**Issue by aashidham** [pocesar/node-stratum#11]
I've used the client.js inside the example directory and tried to connect to a remote stratum server: https://gist.github.com/aashidham/dd33b949d8ad4eb9ba57301b7888065e

But it fails with 'connection closed'. Any idea why?

**Comment by pocesar** [comment]
that code is for demonstration only, it sends fake data when connecting, that's why it's disconnecting you right way

**Comment by aashidham** [comment]
It disconnects even before authorizatjon, even before it sends fake data.

**Comment by pocesar** [comment]
before executing the client, set the environment variable `set DEBUG=stratum,jsonrpc` in your command line (`export` if you in linux), you'll see what's happening underneath

**Comment by mersed** [comment]
I am having exactly the same issue right now. For multiple remote popular pools which supports stratum protocol, i am getting "Connection closed" right after trying to connect to the pool.

**Comment by marslan390** [comment]
I am having the same issue as well.

**Comment by marslan390** [comment]
@mersed @aashidham did you get some other way to connect?

**Comment by envman** [comment]
Added https://github.com/envman/node-stratum/commit/84605482d433072aa989082be8cb6160e0c6310d to send the error out.

then the following error code shows the socket error:
```
client.on('error', function(socket, e) {
  socket.destroy();
  console.log('Connection closed', e);
  process.exit(1);
});
```

mine was ENOTFOUND, removed the stratum+tcp:// from the start of the address and it worked.

**Comment by pocesar** [comment]
@envman thanks for that, can you make the PR? I'll merge it (as it's not a breaking change)

**Comment by envman** [comment]
https://github.com/pocesar/node-stratum/pull/16

Not sure if it's worth adding some checks to make sure the URL is correct, could auto remove stratum+tcp:// maybe?

**Comment by pocesar** [comment]
maybe that could be added to the README, because, indeed, stratum+tcp is not a valid protocol per se

**Comment by marslan390** [comment]
Thank you @envman, now i am getting this error:
Web server listening on port 8080
undefined 'us1-zcash.flypool.org'
{ Error: connect EADDRNOTAVAIL 192.99.33.207 - Local (0.0.0.0:49860)
    at Object._errnoException (util.js:1019:11)
    at _exceptionWithHostPort (util.js:1041:20)
    at internalConnect (net.js:964:16)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1099:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:100:10)
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'connect',
  address: '192.99.33.207' }
Connection closed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stratum@0.2.5 start: `node app.js`
npm ERR! Exit status 1

Is this something you can help me?

**Comment by marslan390** [comment]
@pocesar Thanks :-)

**Comment by envman** [comment]
added to readme, just check you're happy with the way I wrote it ;)

**Comment by mersed** [comment]
@marslan390 Are you able to use the client in order to connect with the remote server? Indeed, removing "stratum+tcp" will allow you to connect to the server, but I am still encountering few issues.

After the connection, I am sending the subscribe and I am getting appropriate response to that call. After that, sending authorize, but response is not what I am expecting to be:

With socket.stratumAuthorize(stratumUsername, stratumPassword) we are sending:
`{"params": ["slush.miner1", "password"], "id": 2, "method": "mining.authorize"}\n`
And we are expecting: 
`{"error": null, "id": 2, "result": true}\n`

but that actually is not what happens. In this case on "socket.stratumAuthorize()" im getting the same response from the server as on socket.stratumSubscribe() .

Tested against https://www.litecoinpool.org and few other servers/pools.

**Comment by joepvandepol** [comment]
@mersed did you got it working?
